bi:
  messaging:
    requestDestination: 'test.out'
    replyDestination: 'test.in'
    receiveTimeout: 10000
    replyTimeout: 10000

# the default URL for embedded ActiveMQ connection factory
brokerURL: 'vm://localhost?broker.persistent=false'

---

spring:
  profiles: 'bi-consumer'
server:
    port: 9000




