bi:
  messaging:
    requestDestination: 'test.out'
    replyDestination: 'test.in'
    receiveTimeout: 10000
    replyTimeout: 10000

# the default URL for embedded ActiveMQ connection factory
brokerURL: 'vm://localhost?broker.persistent=false'

---

spring:
  profiles: 'bi-consumer'
server:
    port: 9000

---

spring:
  profiles: 'rabbitmq'
brokerURL: ''


---

spring:
  profiles: 'kafka'
brokerURL: 'localhost:9092'
zookeeperURL: 'localhost:2181'

kafka:
  producer:
    retriesConfig: 0
    batchSizeConfig: 16384
    lingerMsConfig: 1
    bufferMemoryConfig: 33554432
  consumer:
    groupIdConfig: 'testGroup'
    enableAutoCommitConfig: true
    autoCommitIntervalMsConfig: 100
    sessionTimeoutMsConfig: 15000
  messageKeyRequest: bi.key.request
  messageKeyReply: bi.key.reply




